// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/cf-tcp-router/metrics_reporter/haproxy_client"
)

type FakeHaproxyClient struct {
	GetStatsStub        func() haproxy_client.HaproxyStats
	getStatsMutex       sync.RWMutex
	getStatsArgsForCall []struct{}
	getStatsReturns     struct {
		result1 haproxy_client.HaproxyStats
	}
}

func (fake *FakeHaproxyClient) GetStats() haproxy_client.HaproxyStats {
	fake.getStatsMutex.Lock()
	fake.getStatsArgsForCall = append(fake.getStatsArgsForCall, struct{}{})
	fake.getStatsMutex.Unlock()
	if fake.GetStatsStub != nil {
		return fake.GetStatsStub()
	} else {
		return fake.getStatsReturns.result1
	}
}

func (fake *FakeHaproxyClient) GetStatsCallCount() int {
	fake.getStatsMutex.RLock()
	defer fake.getStatsMutex.RUnlock()
	return len(fake.getStatsArgsForCall)
}

func (fake *FakeHaproxyClient) GetStatsReturns(result1 haproxy_client.HaproxyStats) {
	fake.GetStatsStub = nil
	fake.getStatsReturns = struct {
		result1 haproxy_client.HaproxyStats
	}{result1}
}

var _ haproxy_client.HaproxyClient = new(FakeHaproxyClient)
