// This file was generated by counterfeiter
package fake_generator

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"code.cloudfoundry.org/operationq"
	"code.cloudfoundry.org/rep/generator"
)

type FakeGenerator struct {
	BatchOperationsStub        func(lager.Logger) (map[string]operationq.Operation, error)
	batchOperationsMutex       sync.RWMutex
	batchOperationsArgsForCall []struct {
		arg1 lager.Logger
	}
	batchOperationsReturns struct {
		result1 map[string]operationq.Operation
		result2 error
	}
	OperationStreamStub        func(lager.Logger) (<-chan operationq.Operation, error)
	operationStreamMutex       sync.RWMutex
	operationStreamArgsForCall []struct {
		arg1 lager.Logger
	}
	operationStreamReturns struct {
		result1 <-chan operationq.Operation
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGenerator) BatchOperations(arg1 lager.Logger) (map[string]operationq.Operation, error) {
	fake.batchOperationsMutex.Lock()
	fake.batchOperationsArgsForCall = append(fake.batchOperationsArgsForCall, struct {
		arg1 lager.Logger
	}{arg1})
	fake.recordInvocation("BatchOperations", []interface{}{arg1})
	fake.batchOperationsMutex.Unlock()
	if fake.BatchOperationsStub != nil {
		return fake.BatchOperationsStub(arg1)
	} else {
		return fake.batchOperationsReturns.result1, fake.batchOperationsReturns.result2
	}
}

func (fake *FakeGenerator) BatchOperationsCallCount() int {
	fake.batchOperationsMutex.RLock()
	defer fake.batchOperationsMutex.RUnlock()
	return len(fake.batchOperationsArgsForCall)
}

func (fake *FakeGenerator) BatchOperationsArgsForCall(i int) lager.Logger {
	fake.batchOperationsMutex.RLock()
	defer fake.batchOperationsMutex.RUnlock()
	return fake.batchOperationsArgsForCall[i].arg1
}

func (fake *FakeGenerator) BatchOperationsReturns(result1 map[string]operationq.Operation, result2 error) {
	fake.BatchOperationsStub = nil
	fake.batchOperationsReturns = struct {
		result1 map[string]operationq.Operation
		result2 error
	}{result1, result2}
}

func (fake *FakeGenerator) OperationStream(arg1 lager.Logger) (<-chan operationq.Operation, error) {
	fake.operationStreamMutex.Lock()
	fake.operationStreamArgsForCall = append(fake.operationStreamArgsForCall, struct {
		arg1 lager.Logger
	}{arg1})
	fake.recordInvocation("OperationStream", []interface{}{arg1})
	fake.operationStreamMutex.Unlock()
	if fake.OperationStreamStub != nil {
		return fake.OperationStreamStub(arg1)
	} else {
		return fake.operationStreamReturns.result1, fake.operationStreamReturns.result2
	}
}

func (fake *FakeGenerator) OperationStreamCallCount() int {
	fake.operationStreamMutex.RLock()
	defer fake.operationStreamMutex.RUnlock()
	return len(fake.operationStreamArgsForCall)
}

func (fake *FakeGenerator) OperationStreamArgsForCall(i int) lager.Logger {
	fake.operationStreamMutex.RLock()
	defer fake.operationStreamMutex.RUnlock()
	return fake.operationStreamArgsForCall[i].arg1
}

func (fake *FakeGenerator) OperationStreamReturns(result1 <-chan operationq.Operation, result2 error) {
	fake.OperationStreamStub = nil
	fake.operationStreamReturns = struct {
		result1 <-chan operationq.Operation
		result2 error
	}{result1, result2}
}

func (fake *FakeGenerator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.batchOperationsMutex.RLock()
	defer fake.batchOperationsMutex.RUnlock()
	fake.operationStreamMutex.RLock()
	defer fake.operationStreamMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeGenerator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ generator.Generator = new(FakeGenerator)
