// This file was generated by counterfeiter
// with command: counterfeiter -p -o /Users/pivotal/workspace/local-volume-release/src/code.cloudfoundry.org/goshims/ioutil io/ioutil
package ioutilshim

import (
	"io"
	"io/ioutil"
	"os"
)

type IoutilShim struct{}

func (sh *IoutilShim) ReadAll(r io.Reader) ([]byte, error) {
	return ioutil.ReadAll(r)
}

func (sh *IoutilShim) ReadFile(filename string) ([]byte, error) {
	return ioutil.ReadFile(filename)
}

func (sh *IoutilShim) WriteFile(filename string, data []byte, perm os.FileMode) error {
	return ioutil.WriteFile(filename, data, perm)
}

func (sh *IoutilShim) ReadDir(dirname string) ([]os.FileInfo, error) {
	return ioutil.ReadDir(dirname)
}

func (sh *IoutilShim) NopCloser(r io.Reader) io.ReadCloser {
	return ioutil.NopCloser(r)
}

func (sh *IoutilShim) TempFile(dir string, prefix string) (f *os.File, err error) {
	return ioutil.TempFile(dir, prefix)
}

func (sh *IoutilShim) TempDir(dir string, prefix string) (name string, err error) {
	return ioutil.TempDir(dir, prefix)
}
