// This file was generated by counterfeiter
package repfakes

import (
	"sync"

	"code.cloudfoundry.org/rep"
)

type FakeClientFactory struct {
	CreateClientStub        func(address, url string) (rep.Client, error)
	createClientMutex       sync.RWMutex
	createClientArgsForCall []struct {
		address string
		url     string
	}
	createClientReturns struct {
		result1 rep.Client
		result2 error
	}
	createClientReturnsOnCall map[int]struct {
		result1 rep.Client
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClientFactory) CreateClient(address string, url string) (rep.Client, error) {
	fake.createClientMutex.Lock()
	ret, specificReturn := fake.createClientReturnsOnCall[len(fake.createClientArgsForCall)]
	fake.createClientArgsForCall = append(fake.createClientArgsForCall, struct {
		address string
		url     string
	}{address, url})
	fake.recordInvocation("CreateClient", []interface{}{address, url})
	fake.createClientMutex.Unlock()
	if fake.CreateClientStub != nil {
		return fake.CreateClientStub(address, url)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createClientReturns.result1, fake.createClientReturns.result2
}

func (fake *FakeClientFactory) CreateClientCallCount() int {
	fake.createClientMutex.RLock()
	defer fake.createClientMutex.RUnlock()
	return len(fake.createClientArgsForCall)
}

func (fake *FakeClientFactory) CreateClientArgsForCall(i int) (string, string) {
	fake.createClientMutex.RLock()
	defer fake.createClientMutex.RUnlock()
	return fake.createClientArgsForCall[i].address, fake.createClientArgsForCall[i].url
}

func (fake *FakeClientFactory) CreateClientReturns(result1 rep.Client, result2 error) {
	fake.CreateClientStub = nil
	fake.createClientReturns = struct {
		result1 rep.Client
		result2 error
	}{result1, result2}
}

func (fake *FakeClientFactory) CreateClientReturnsOnCall(i int, result1 rep.Client, result2 error) {
	fake.CreateClientStub = nil
	if fake.createClientReturnsOnCall == nil {
		fake.createClientReturnsOnCall = make(map[int]struct {
			result1 rep.Client
			result2 error
		})
	}
	fake.createClientReturnsOnCall[i] = struct {
		result1 rep.Client
		result2 error
	}{result1, result2}
}

func (fake *FakeClientFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createClientMutex.RLock()
	defer fake.createClientMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeClientFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rep.ClientFactory = new(FakeClientFactory)
