// Code generated by counterfeiter. DO NOT EDIT.
package fake_log_streamer

import (
	"io"
	"sync"

	"code.cloudfoundry.org/executor/depot/log_streamer"
)

type FakeLogStreamer struct {
	StdoutStub        func() io.Writer
	stdoutMutex       sync.RWMutex
	stdoutArgsForCall []struct{}
	stdoutReturns     struct {
		result1 io.Writer
	}
	stdoutReturnsOnCall map[int]struct {
		result1 io.Writer
	}
	StderrStub        func() io.Writer
	stderrMutex       sync.RWMutex
	stderrArgsForCall []struct{}
	stderrReturns     struct {
		result1 io.Writer
	}
	stderrReturnsOnCall map[int]struct {
		result1 io.Writer
	}
	FlushStub             func()
	flushMutex            sync.RWMutex
	flushArgsForCall      []struct{}
	WithSourceStub        func(sourceName string) log_streamer.LogStreamer
	withSourceMutex       sync.RWMutex
	withSourceArgsForCall []struct {
		sourceName string
	}
	withSourceReturns struct {
		result1 log_streamer.LogStreamer
	}
	withSourceReturnsOnCall map[int]struct {
		result1 log_streamer.LogStreamer
	}
	SourceNameStub        func() string
	sourceNameMutex       sync.RWMutex
	sourceNameArgsForCall []struct{}
	sourceNameReturns     struct {
		result1 string
	}
	sourceNameReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLogStreamer) Stdout() io.Writer {
	fake.stdoutMutex.Lock()
	ret, specificReturn := fake.stdoutReturnsOnCall[len(fake.stdoutArgsForCall)]
	fake.stdoutArgsForCall = append(fake.stdoutArgsForCall, struct{}{})
	fake.recordInvocation("Stdout", []interface{}{})
	fake.stdoutMutex.Unlock()
	if fake.StdoutStub != nil {
		return fake.StdoutStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.stdoutReturns.result1
}

func (fake *FakeLogStreamer) StdoutCallCount() int {
	fake.stdoutMutex.RLock()
	defer fake.stdoutMutex.RUnlock()
	return len(fake.stdoutArgsForCall)
}

func (fake *FakeLogStreamer) StdoutReturns(result1 io.Writer) {
	fake.StdoutStub = nil
	fake.stdoutReturns = struct {
		result1 io.Writer
	}{result1}
}

func (fake *FakeLogStreamer) StdoutReturnsOnCall(i int, result1 io.Writer) {
	fake.StdoutStub = nil
	if fake.stdoutReturnsOnCall == nil {
		fake.stdoutReturnsOnCall = make(map[int]struct {
			result1 io.Writer
		})
	}
	fake.stdoutReturnsOnCall[i] = struct {
		result1 io.Writer
	}{result1}
}

func (fake *FakeLogStreamer) Stderr() io.Writer {
	fake.stderrMutex.Lock()
	ret, specificReturn := fake.stderrReturnsOnCall[len(fake.stderrArgsForCall)]
	fake.stderrArgsForCall = append(fake.stderrArgsForCall, struct{}{})
	fake.recordInvocation("Stderr", []interface{}{})
	fake.stderrMutex.Unlock()
	if fake.StderrStub != nil {
		return fake.StderrStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.stderrReturns.result1
}

func (fake *FakeLogStreamer) StderrCallCount() int {
	fake.stderrMutex.RLock()
	defer fake.stderrMutex.RUnlock()
	return len(fake.stderrArgsForCall)
}

func (fake *FakeLogStreamer) StderrReturns(result1 io.Writer) {
	fake.StderrStub = nil
	fake.stderrReturns = struct {
		result1 io.Writer
	}{result1}
}

func (fake *FakeLogStreamer) StderrReturnsOnCall(i int, result1 io.Writer) {
	fake.StderrStub = nil
	if fake.stderrReturnsOnCall == nil {
		fake.stderrReturnsOnCall = make(map[int]struct {
			result1 io.Writer
		})
	}
	fake.stderrReturnsOnCall[i] = struct {
		result1 io.Writer
	}{result1}
}

func (fake *FakeLogStreamer) Flush() {
	fake.flushMutex.Lock()
	fake.flushArgsForCall = append(fake.flushArgsForCall, struct{}{})
	fake.recordInvocation("Flush", []interface{}{})
	fake.flushMutex.Unlock()
	if fake.FlushStub != nil {
		fake.FlushStub()
	}
}

func (fake *FakeLogStreamer) FlushCallCount() int {
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	return len(fake.flushArgsForCall)
}

func (fake *FakeLogStreamer) WithSource(sourceName string) log_streamer.LogStreamer {
	fake.withSourceMutex.Lock()
	ret, specificReturn := fake.withSourceReturnsOnCall[len(fake.withSourceArgsForCall)]
	fake.withSourceArgsForCall = append(fake.withSourceArgsForCall, struct {
		sourceName string
	}{sourceName})
	fake.recordInvocation("WithSource", []interface{}{sourceName})
	fake.withSourceMutex.Unlock()
	if fake.WithSourceStub != nil {
		return fake.WithSourceStub(sourceName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.withSourceReturns.result1
}

func (fake *FakeLogStreamer) WithSourceCallCount() int {
	fake.withSourceMutex.RLock()
	defer fake.withSourceMutex.RUnlock()
	return len(fake.withSourceArgsForCall)
}

func (fake *FakeLogStreamer) WithSourceArgsForCall(i int) string {
	fake.withSourceMutex.RLock()
	defer fake.withSourceMutex.RUnlock()
	return fake.withSourceArgsForCall[i].sourceName
}

func (fake *FakeLogStreamer) WithSourceReturns(result1 log_streamer.LogStreamer) {
	fake.WithSourceStub = nil
	fake.withSourceReturns = struct {
		result1 log_streamer.LogStreamer
	}{result1}
}

func (fake *FakeLogStreamer) WithSourceReturnsOnCall(i int, result1 log_streamer.LogStreamer) {
	fake.WithSourceStub = nil
	if fake.withSourceReturnsOnCall == nil {
		fake.withSourceReturnsOnCall = make(map[int]struct {
			result1 log_streamer.LogStreamer
		})
	}
	fake.withSourceReturnsOnCall[i] = struct {
		result1 log_streamer.LogStreamer
	}{result1}
}

func (fake *FakeLogStreamer) SourceName() string {
	fake.sourceNameMutex.Lock()
	ret, specificReturn := fake.sourceNameReturnsOnCall[len(fake.sourceNameArgsForCall)]
	fake.sourceNameArgsForCall = append(fake.sourceNameArgsForCall, struct{}{})
	fake.recordInvocation("SourceName", []interface{}{})
	fake.sourceNameMutex.Unlock()
	if fake.SourceNameStub != nil {
		return fake.SourceNameStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.sourceNameReturns.result1
}

func (fake *FakeLogStreamer) SourceNameCallCount() int {
	fake.sourceNameMutex.RLock()
	defer fake.sourceNameMutex.RUnlock()
	return len(fake.sourceNameArgsForCall)
}

func (fake *FakeLogStreamer) SourceNameReturns(result1 string) {
	fake.SourceNameStub = nil
	fake.sourceNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeLogStreamer) SourceNameReturnsOnCall(i int, result1 string) {
	fake.SourceNameStub = nil
	if fake.sourceNameReturnsOnCall == nil {
		fake.sourceNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.sourceNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeLogStreamer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.stdoutMutex.RLock()
	defer fake.stdoutMutex.RUnlock()
	fake.stderrMutex.RLock()
	defer fake.stderrMutex.RUnlock()
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	fake.withSourceMutex.RLock()
	defer fake.withSourceMutex.RUnlock()
	fake.sourceNameMutex.RLock()
	defer fake.sourceNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLogStreamer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ log_streamer.LogStreamer = new(FakeLogStreamer)
