#!/bin/bash -exu

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"

docker run \
  -v "${ROOT_DIR}":/etcd-metrics-server \
  cfinfrastructure/golang \
  /etcd-metrics-server/scripts/ci/test
