// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/route-emitter/emitter"
	"code.cloudfoundry.org/route-emitter/routingtable"
)

type FakeNATSEmitter struct {
	EmitStub        func(messagesToEmit routingtable.MessagesToEmit) error
	emitMutex       sync.RWMutex
	emitArgsForCall []struct {
		messagesToEmit routingtable.MessagesToEmit
	}
	emitReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNATSEmitter) Emit(messagesToEmit routingtable.MessagesToEmit) error {
	fake.emitMutex.Lock()
	fake.emitArgsForCall = append(fake.emitArgsForCall, struct {
		messagesToEmit routingtable.MessagesToEmit
	}{messagesToEmit})
	fake.recordInvocation("Emit", []interface{}{messagesToEmit})
	fake.emitMutex.Unlock()
	if fake.EmitStub != nil {
		return fake.EmitStub(messagesToEmit)
	} else {
		return fake.emitReturns.result1
	}
}

func (fake *FakeNATSEmitter) EmitCallCount() int {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return len(fake.emitArgsForCall)
}

func (fake *FakeNATSEmitter) EmitArgsForCall(i int) routingtable.MessagesToEmit {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return fake.emitArgsForCall[i].messagesToEmit
}

func (fake *FakeNATSEmitter) EmitReturns(result1 error) {
	fake.EmitStub = nil
	fake.emitReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNATSEmitter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeNATSEmitter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ emitter.NATSEmitter = new(FakeNATSEmitter)
