// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"github.com/cloudfoundry/blobstore_url_signer/server"
)

type FakeServerHandlers struct {
	SignUrlStub        func(w http.ResponseWriter, r *http.Request)
	signUrlMutex       sync.RWMutex
	signUrlArgsForCall []struct {
		w http.ResponseWriter
		r *http.Request
	}
}

func (fake *FakeServerHandlers) SignUrl(w http.ResponseWriter, r *http.Request) {
	fake.signUrlMutex.Lock()
	fake.signUrlArgsForCall = append(fake.signUrlArgsForCall, struct {
		w http.ResponseWriter
		r *http.Request
	}{w, r})
	fake.signUrlMutex.Unlock()
	if fake.SignUrlStub != nil {
		fake.SignUrlStub(w, r)
	}
}

func (fake *FakeServerHandlers) SignUrlCallCount() int {
	fake.signUrlMutex.RLock()
	defer fake.signUrlMutex.RUnlock()
	return len(fake.signUrlArgsForCall)
}

func (fake *FakeServerHandlers) SignUrlArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.signUrlMutex.RLock()
	defer fake.signUrlMutex.RUnlock()
	return fake.signUrlArgsForCall[i].w, fake.signUrlArgsForCall[i].r
}

var _ server.ServerHandlers = new(FakeServerHandlers)
