// This file was generated by counterfeiter
// with command: counterfeiter -p os/exec
package execshim

import "os/exec"

type ExecShim struct{}

func (sh *ExecShim) Command(name string, arg ...string) Cmd {
	return exec.Command(name, arg...)
}

func (sh *ExecShim) LookPath(file string) (string, error) {
	return exec.LookPath(file)
}
