#!/bin/bash -eux

function main() {
  local scripts_dir
  scripts_dir=$(cd "$(dirname "${0}")" && pwd)

  local root_dir
  root_dir=$(cd "${scripts_dir}/.." && pwd)

  export GO15VENDOREXPERIMENT=1
  export PATH="${root_dir}/bin:${PATH}"

  install_ginkgo "${root_dir}"
  pushd "${root_dir}" > /dev/null
    ginkgo \
      -race \
      -succinct \
      precheck

    ginkgo \
      -r \
      -race \
      -randomizeAllSpecs \
      -randomizeSuites \
      -failFast \
      -succinct \
      -skipPackage precheck \
      -skipPackage cf-tls-upgrade \
      -slowSpecThreshold 300 \
      "$@"
  popd > /dev/null
}

function install_ginkgo() {
  local dir
  dir="${1}"

  mkdir -p "${dir}/src/github.com/onsi"
  pushd "${dir}/src/github.com/onsi" > /dev/null
    ln -sf "${dir}/vendor/github.com/onsi/ginkgo"
    GOPATH="${dir}" go install github.com/onsi/ginkgo/ginkgo
  popd > /dev/null
  rm "${dir}/src/github.com/onsi/ginkgo"
}

main "$@"
