#!/bin/bash

set -eu
set -o pipefail

pushd packages/confab
  {
    cat spec | grep -v '# gosub'
    gosub list -a confab/confab/... | \
      sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
  } > spec.new

  mv spec.new spec
popd
