// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/blobstore_url_signer/signer"
)

type FakeSigner struct {
	SignStub        func(string, string) string
	signMutex       sync.RWMutex
	signArgsForCall []struct {
		arg1 string
		arg2 string
	}
	signReturns struct {
		result1 string
	}
}

func (fake *FakeSigner) Sign(arg1 string, arg2 string) string {
	fake.signMutex.Lock()
	fake.signArgsForCall = append(fake.signArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.signMutex.Unlock()
	if fake.SignStub != nil {
		return fake.SignStub(arg1, arg2)
	} else {
		return fake.signReturns.result1
	}
}

func (fake *FakeSigner) SignCallCount() int {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return len(fake.signArgsForCall)
}

func (fake *FakeSigner) SignArgsForCall(i int) (string, string) {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return fake.signArgsForCall[i].arg1, fake.signArgsForCall[i].arg2
}

func (fake *FakeSigner) SignReturns(result1 string) {
	fake.SignStub = nil
	fake.signReturns = struct {
		result1 string
	}{result1}
}

var _ signer.Signer = new(FakeSigner)
