// This file was generated by counterfeiter
package fakes

import (
	"os"
	"sync"

	"code.cloudfoundry.org/auction/auctiontypes"
	"code.cloudfoundry.org/auctioneer"
)

type FakeAuctionRunner struct {
	RunStub        func(signals <-chan os.Signal, ready chan<- struct{}) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		signals <-chan os.Signal
		ready   chan<- struct{}
	}
	runReturns struct {
		result1 error
	}
	ScheduleLRPsForAuctionsStub        func([]auctioneer.LRPStartRequest)
	scheduleLRPsForAuctionsMutex       sync.RWMutex
	scheduleLRPsForAuctionsArgsForCall []struct {
		arg1 []auctioneer.LRPStartRequest
	}
	ScheduleTasksForAuctionsStub        func([]auctioneer.TaskStartRequest)
	scheduleTasksForAuctionsMutex       sync.RWMutex
	scheduleTasksForAuctionsArgsForCall []struct {
		arg1 []auctioneer.TaskStartRequest
	}
}

func (fake *FakeAuctionRunner) Run(signals <-chan os.Signal, ready chan<- struct{}) error {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		signals <-chan os.Signal
		ready   chan<- struct{}
	}{signals, ready})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(signals, ready)
	} else {
		return fake.runReturns.result1
	}
}

func (fake *FakeAuctionRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeAuctionRunner) RunArgsForCall(i int) (<-chan os.Signal, chan<- struct{}) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].signals, fake.runArgsForCall[i].ready
}

func (fake *FakeAuctionRunner) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuctionRunner) ScheduleLRPsForAuctions(arg1 []auctioneer.LRPStartRequest) {
	fake.scheduleLRPsForAuctionsMutex.Lock()
	fake.scheduleLRPsForAuctionsArgsForCall = append(fake.scheduleLRPsForAuctionsArgsForCall, struct {
		arg1 []auctioneer.LRPStartRequest
	}{arg1})
	fake.scheduleLRPsForAuctionsMutex.Unlock()
	if fake.ScheduleLRPsForAuctionsStub != nil {
		fake.ScheduleLRPsForAuctionsStub(arg1)
	}
}

func (fake *FakeAuctionRunner) ScheduleLRPsForAuctionsCallCount() int {
	fake.scheduleLRPsForAuctionsMutex.RLock()
	defer fake.scheduleLRPsForAuctionsMutex.RUnlock()
	return len(fake.scheduleLRPsForAuctionsArgsForCall)
}

func (fake *FakeAuctionRunner) ScheduleLRPsForAuctionsArgsForCall(i int) []auctioneer.LRPStartRequest {
	fake.scheduleLRPsForAuctionsMutex.RLock()
	defer fake.scheduleLRPsForAuctionsMutex.RUnlock()
	return fake.scheduleLRPsForAuctionsArgsForCall[i].arg1
}

func (fake *FakeAuctionRunner) ScheduleTasksForAuctions(arg1 []auctioneer.TaskStartRequest) {
	fake.scheduleTasksForAuctionsMutex.Lock()
	fake.scheduleTasksForAuctionsArgsForCall = append(fake.scheduleTasksForAuctionsArgsForCall, struct {
		arg1 []auctioneer.TaskStartRequest
	}{arg1})
	fake.scheduleTasksForAuctionsMutex.Unlock()
	if fake.ScheduleTasksForAuctionsStub != nil {
		fake.ScheduleTasksForAuctionsStub(arg1)
	}
}

func (fake *FakeAuctionRunner) ScheduleTasksForAuctionsCallCount() int {
	fake.scheduleTasksForAuctionsMutex.RLock()
	defer fake.scheduleTasksForAuctionsMutex.RUnlock()
	return len(fake.scheduleTasksForAuctionsArgsForCall)
}

func (fake *FakeAuctionRunner) ScheduleTasksForAuctionsArgsForCall(i int) []auctioneer.TaskStartRequest {
	fake.scheduleTasksForAuctionsMutex.RLock()
	defer fake.scheduleTasksForAuctionsMutex.RUnlock()
	return fake.scheduleTasksForAuctionsArgsForCall[i].arg1
}

var _ auctiontypes.AuctionRunner = new(FakeAuctionRunner)
